name: SCA

on:
  push:
    branches: ["master", "main"]

jobs:
  snyk-cli:
    uses: auth0/devsecops-tooling/.github/workflows/sca-scan@main
    with:
      additional-arguments: "--exclude=README.md,.jfrog"
      dotnet-version: "10.0"
    secrets: inherit